### ISSUE TITLE
Clarification on Fixed Visual Token Counts (192, 128, 64) in Table 1

### ISSUE THREAD

**Issue by naajeehxe** [Gumpest/SparseVLMs#10]
Hello, Thanks for your wonderful research. 

I understand that the number of tokens being pruned depends on the value of  lambda  multiplied by the rank, while the number of recycled tokens is influenced by the hyper parameter  tau .

But the table1 of this paper shows that the number of visual tokens is fixed at 192, 128, and 64. 

Could you please clarify whether these token counts were hardcoded to select exactly 192, 128, or 64 visual tokens, or if there was another approach to maintaining a fixed token count for these experiments?

Thank you, Sincerely

**Comment by Gumpest** [comment]
I appreciate your interest in our work.

1. The retained tokens are controlled by changing the scaling factor in **Formula 8**.
2. This is the equivalent number of tokens. For example, `T = {(L1-L0) * T0 + (L2-L1) * T1} / L2`.
3. Therefore, we select exactly 192, 128, or 64 visual tokens to compare with other methods fairly.

**Comment by YUECHE77** [comment]
Hi, 

I'm also very curious about the configuration in tabel 1. Could you please us an example?

For instance, when you retain exactly 128 tokens, what is your "--scale" and "--bias"? Are they 9 and 6? Please correct me if I'm wrong.

Also, I'm kind of confused about the meaning of "scale" and "bias". Does "scale" stand for the lambda in Formula 8? And what is "bias" exactly?

And by the way, could you please share the configuration for FastV in table 1? I'm trying to reproduce your results. What k (layer) and r (attention rank) were you using, for example "Retain 128 Tokens" as you mentioned in table 1?

![image](https://github.com/user-attachments/assets/25228f68-5e19-4757-866d-d5e3dc5ca1c4)

Really like your work, it's amazing! And hope I can get your respond.

Thank you!

**Comment by Osilly** [comment]
@YUECHE77 Can you provide the results your reproduced ? Our results are as follows:

|                     | Token number | VQAv2 | GQA | SQA   |
| ------------------- | ------------ | ---------- | ----- | ----- |
| True FastV (using official code)          | 171          | 74.06      | 56.58 | 69.06 |
| FastV in your paper | 192          | 67.1       | 52.7   | 67.3  |
| SparseVLM           | 192          | 75.6       | 57.6  | 69.1  |

Specifically, we set [this line in the official repo of FastV](https://github.com/pkunlp-icler/FastV/blob/main/src/FastV/lmms-eval/fastv_kvcache.py#L119) to K=2, ratio = 0.25, and the equivalent token calculation is as follows:

`T = (576 * 2 + 144 * 30) / 32 = 171` when we set K=2, ratio = 0.25.

Unfortunately, this seems to indicate that this work significantly depresses baseline performance, or at least uses unfair settings. We've given up trying to reproduce the results of this work.

**Comment by YUECHE77** [comment]
Hi,

Thanks for the reply and and the formula you provide. But actually I only focused on the POPE dataset. I also used different configuration with k=3, r=0.5.

The result I got is Acc=85.24 and F1=83.52

**Comment by xinlong-yang** [comment]
> @YUECHE77 Can you provide the results your reproduced ? Our results are as follows:
> 
> Token number	VQAv2	GQA	SQA
> True FastV (using official code)	171	74.06	56.58	69.06
> FastV in your paper	192	67.1	52.7	67.3
> SparseVLM	192	75.6	57.6	69.1
> Specifically, we set [this line in the official repo of FastV](https://github.com/pkunlp-icler/FastV/blob/main/src/FastV/lmms-eval/fastv_kvcache.py#L119) to K=2, ratio = 0.25, and the equivalent token calculation is as follows:
> 
> `T = (576 * 2 + 144 * 30) / 32 = 171` when we set K=2, ratio = 0.25.
> 
> Unfortunately, this seems to indicate that this work significantly depresses baseline performance, or at least uses unfair settings. We've given up trying to reproduce the results of this work.

And we find that it's hard to align the configuration, if we set the image number to be fixed, then what's the use of **rank** of the attention score matrix?
