### ISSUE TITLE
 I would like to know which files' code you modified?

### ISSUE THREAD

**Issue by FanshuoZeng** [Gumpest/SparseVLMs#3]
This is a very meaningful work. I would like to know which files' code you modified? Can you tell me?

**Comment by Gumpest** [comment]
Thanks a lot. The core additions are mainly from https://github.com/Gumpest/SparseVLMs/blob/main/llava/model/language_model/modelling_sparse_llama.py#L201

**Comment by Gumpest** [comment]
<img width="1373" alt="image" src="https://github.com/user-attachments/assets/4754ddc1-d3f7-4fcd-a7f1-4a12ef3c05c7">
The above four files are our main contributions.

**Comment by FanshuoZeng** [comment]
Thanks!
