### ISSUE TITLE
token number

### ISSUE THREAD

**Issue by Yxxxb** [Gumpest/SparseVLMs#4]
Hi, 

I was wondering if the retain (192/128/64) tokens setting you report in Table 1 are controlled by changing the scaling factor in the formula below?
<img width="592" alt="image" src="https://github.com/user-attachments/assets/fa1eead5-9732-41aa-b9ef-69cd75583f14">
Besides, is the number of tokens pruned to the last layer? Or the first layer? Because I understand that you pruned at each layer of LLM.

Thanks!

**Comment by Gumpest** [comment]
I appreciate your interest in our work. 

- The retained tokens are controlled by changing the scaling factor in **Formula 8**.
- This is the **equivalent number of tokens**. For example, `T = {(L1-L0) * T0 + (L2-L1) * T1} / L2.`
