### ISSUE TITLE
How to get attn_logits when using flash-attention?

### ISSUE THREAD

**Issue by Naive-Bayes** [Gumpest/SparseVLMs#6]
In 'LlamaDynamicvitFlashAttention2', hardly set output_attentions = False (https://github.com/Gumpest/SparseVLMs/blob/7fc55f02610fc1c898d44f18906c4f7f4eeffca5/llava/model/language_model/modelling_sparse_llama.py#L497).

So, how to get attn_logits when using flash-attention?

**Comment by Gumpest** [comment]
Thank you for your interest in our work. In the actual code, we use the SDPA operator instead of FlashAttention to implement the attention operation, which can output attention.

https://github.com/Gumpest/SparseVLMs/blob/main/llava/model/language_model/modelling_sparse_llama.py#L675

**Comment by Naive-Bayes** [comment]
> Thank you for your interest in our work. In the actual code, we use the SDPA operator instead of FlashAttention to implement the attention operation, which can output attn_logits.
> 
> https://github.com/Gumpest/SparseVLMs/blob/main/llava/model/language_model/modelling_sparse_llama.py#L675

Thanks for reply. Have you tested the time consuming between SDPA and FlashAttention?

**Comment by Gumpest** [comment]
@Naive-Bayes Sorry, I do not pay attention to the speed differences of the operators. Instead, I focus more on the optimizations brought about by sparsification.

**Comment by Cooperx521** [comment]
https://github.com/Gumpest/SparseVLMs/blob/b72c5d62fa7004c2f1440c75975981bddf6c66c7/llava/model/language_model/modelling_sparse_llama.py#L580
It seems that it will directly come to LlamaSdpaAttention and then come to LlamaAttention when output_attentions = True

**Comment by Naive-Bayes** [comment]
> https://github.com/Gumpest/SparseVLMs/blob/b72c5d62fa7004c2f1440c75975981bddf6c66c7/llava/model/language_model/modelling_sparse_llama.py#L580
> 
> 
> It seems that it will directly come to LlamaSdpaAttention and then come to LlamaAttention when output_attentions = True

Yes, when set output_attentions = True, the decoder layer go back to the naive manuscript implementation, not SDPA. 
So, the key is, how many layers need to output attention weights? If all need, that means we can not use flashattention or sdpa to speed up.
