### ISSUE TITLE
Does table1 use llava-1.5-7b？

### ISSUE THREAD

**Issue by liuting20** [Gumpest/SparseVLMs#9]
llava's eval script does not have LLava-1.5-7b.json files for many data sets，such as SQA. How did you test the performance of SparseVLM in llava-1.5-7b. Look forward to your guidance.

**Comment by Gumpest** [comment]
I appreciate your interest in our work.

We currently provide only 3 types of scripts. The rest of the scripts can be rewritten according to this rule or released after the paper is accepted.
